name: Build Documentation

on:
  push:
    branches:
      - master  # Change this to your default branch if it's not named 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Sphinx

  # Navigate to the 'docs' directory and build the documentation
      - name: Build docs
        run: |
          cd docs
          make html
