name: Update POT file
on:
  workflow_dispatch:
  push:
    paths:
      - 'docs/index.rst'
    branches:
      - 'master'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ammaraskar/sphinx-action@master
        with:
          build-command: "sphinx-build -b gettext . ../"
      - name: Configure git
        run: git config --global user.name "Github Action" && git config --global user.email '<>'
      - name: Install gettext
        run: sudo apt install gettext
      - name: Install sphinx-intl
        run: pip install sphinx-intl
      - name: Dynamically update .po files for all languages
        run: |
          for lang_dir in $(find locales -type d -name LC_MESSAGES); do
            echo "Processing language directory: $lang_dir"
            lang_code=$(basename $(dirname "$lang_dir"))
            sphinx-intl update -p . -l "$lang_code"
          done
      - name: Run msgmerge
        run: find locales -regex ".*index\.po$"  | xargs -I "{}" msgmerge -U {} index.pot --backup=off
      - name: Commit changes
        run: git commit -a -m "Updated doc strings" || echo "No changes"
      - name: Push changes
        run: git push
