name: Update POT file
on:
  push:
    paths:
      - 'docs/index.rst'
    branches:
      - 'master'
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: ammaraskar/sphinx-action@master
          with:
            build-command: "sphinx-build -b gettext docs/ ."
      - uses: actions/checkout@v2
        with:
          repository: 'WorldHealthOrganization/herams-i18n'
          path: 'herams-i18n'
        name: Checkout i18n repo
      - name: Configure git
        run: git config --global user.name "Github Action" && git config --global user.email '<>'
      - name: Commit changes
        run: git commit index.pot -m "Updated doc strings" || echo "No changes"
      - name: Push changes
        run: git push
